use foods;
create table documents (
	documentId INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(512) NOT NULL UNIQUE,
	entityId INT UNSIGNED NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

	PRIMARY KEY(documentId),
	FOREIGN KEY(entityId) REFERENCES entity(entityId)
);